### ISSUE TITLE
Improve robustness of "superbuild" on selected platforms

### ISSUE THREAD

**Issue by jnjohnsonlbl** [LBL-EESA/TECA_superbuild#19]
For TECA's v2.0 release, we aim to support the following platforms:
1. NERSC (Edison/Cori)
2. Linux workstations
3. MacOS workstations (El Capitan)

We should modify the above platform descriptions to reflect any specific constraints we are imposing on folks who want to build and install TECA. For example: to what extent do we advise for or against the use of a given package manager (such as macports or homebrew, on the Mac platform)?

Presently, @HarinarayanKrishnan and I are having issues building TECA from scratch using the superbuild process on MacOS El Capitan. @burlen is going to try to reproduce our issues on this platform.

**Comment by burlen** [comment]
NERSC's new policies, namely annaconda kitchen sink that includes not thread safe netcdf, forced the use of the superbuild.

**Comment by burlen** [comment]
superbuild is running on all the above platforms, I'm closing this task
