### ISSUE TITLE
libxlsxwriter cmake does not pick up custom zlib include directory

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA_superbuild#31]
On an ubuntu 17.04 system (w/out the `zlib1g-dev` apt package installed), cmake fails at the `libxlsxwriter` step b/c the make step for `libxlsxwriter` complains that `zlib.h` is not found.  Setting `VERBOSE=1` prior to building shows that the compile command for `libxlsxwriter` does not include a -I flag pointing to the version of zlib that TECA_superbuild successfully builds and installs in a prior step.

Installing `zlib1g-dev` circumvents this issues.

**Comment by burlen** [comment]
when you missing header files installing the dev packlages solves the issue.
