### ISSUE TITLE
test on recent distros

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA_superbuild#38]
test the superbuild on the latest mac os and recent linux distros, fix any issues that are encountered.

this issue depends on #39 as we know that Fedora 28 requires a newer version of Python

**Comment by elbashandy** [comment]
Look at my comment on #39 

https://github.com/LBL-EESA/TECA_superbuild/issues/39#issuecomment-451600359

**Comment by elbashandy** [comment]
TECA_superbuild was tested on Ubuntu 18:04 & Fedora 28.
